export default {
  id: "kenari",
  priority: 125,
  alias: "kenari",
  aliases: [
    "kn",
  ],
  uiAlias: "kn",
  display: {
    name: "Kenari",
    icon: "flight",
    color: "#0EA5E9",
    textIcon: "KN",
    website: "https://kenari.id",
    notice: {
      text: "Indonesian aggregator (IDR pricing). Supports Chat, Responses, and Claude-compatible endpoints.",
      apiKeyUrl: "https://kenari.id",
    },
  },
  category: "apikey",
  transport: {
    baseUrl: "https://kenari.id/v1/chat/completions",
    validateUrl: "https://kenari.id/v1/models",
    usage: {
      url: "https://kenari.id/v1/account/quota",
    },
    quirks: {
      // /v1/responses only honors flat `function` tools and rejects text.format
      // structured outputs — convert Codex's `custom` exec tool and strip
      // text.format so Codex keeps its native custom-tool wire events.
      responsesFunctionToolsOnly: true,
      // Kenari's Responses endpoint rejects `role:"system"`; fold instructions
      // into the first user turn before dispatch.
      responsesSystemRoleUnsupported: true,
    },
  },
  // Multi-endpoint: Chat + Responses + Claude-compatible. Pick the transport
  // matching the client sourceFormat so most clients skip translation.
  transports: [
    {
      format: "openai",
      baseUrl: "https://kenari.id/v1/chat/completions",
      auth: { combined: true, header: "Authorization", scheme: "bearer" },
    },
    {
      format: "openai-responses",
      baseUrl: "https://kenari.id/v1/responses",
      auth: { combined: true, header: "Authorization", scheme: "bearer" },
    },
    {
      format: "claude",
      baseUrl: "https://kenari.id/v1/messages",
      auth: { combined: true, header: "x-api-key", scheme: "raw" },
    },
  ],
  models: [
    { id: "agnes-2-0-flash:free", name: "agnes-2-0-flash:free" },    { id: "agnes-2-5-flash:free", name: "agnes-2-5-flash:free" },
    { id: "agnes-3-0-flash:free", name: "agnes-3-0-flash:free" },
    { id: "claude-fable-5", name: "claude-fable-5" },
    { id: "claude-opus-4-7", name: "claude-opus-4-7" },
    { id: "claude-opus-4-8", name: "claude-opus-4-8" },
    { id: "claude-opus-5", name: "claude-opus-5" },
    { id: "claude-sonnet-4-6", name: "claude-sonnet-4-6" },
    { id: "claude-sonnet-5", name: "claude-sonnet-5" },
    // Kenari exposes /responses globally, but these DeepSeek models only work
    // reliably through Chat Completions; translate Codex Responses requests.
    { id: "deepseek-v4-1-flash", name: "deepseek-v4-1-flash", supportedFormats: ["openai"] },
    { id: "deepseek-v4-flash", name: "deepseek-v4-flash", supportedFormats: ["openai"] },
    { id: "deepseek-v4-pro", name: "deepseek-v4-pro", supportedFormats: ["openai"] },
    { id: "gemini-2-5-flash", name: "gemini-2-5-flash" },
    { id: "gemini-2-5-flash-lite", name: "gemini-2-5-flash-lite" },
    { id: "gemini-3-1-flash-lite", name: "gemini-3-1-flash-lite" },
    { id: "gemini-3-1-pro", name: "gemini-3-1-pro" },
    { id: "gemini-3-6-flash", name: "gemini-3-6-flash" },
    { id: "gemini-3-7-flash", name: "gemini-3-7-flash" },
    { id: "gemini-3-8-flash", name: "gemini-3-8-flash" },
    { id: "gemma-4-31b-it", name: "gemma-4-31b-it" },
    { id: "glm-4-7-flash:free", name: "glm-4-7-flash:free" },
    { id: "glm-5-2", name: "glm-5-2" },
    { id: "glm-5-3", name: "glm-5-3" },
    { id: "glm-5-3-flash", name: "glm-5-3-flash" },
    { id: "gpt-5-4", name: "gpt-5-4" },
    { id: "gpt-5-4-mini", name: "gpt-5-4-mini" },
    { id: "gpt-5-5", name: "gpt-5-5" },
    { id: "gpt-5-6-luna", name: "gpt-5-6-luna" },
    { id: "gpt-5-6-sol", name: "gpt-5-6-sol" },
    { id: "gpt-5-6-terra", name: "gpt-5-6-terra" },
    { id: "gpt-6-astra", name: "gpt-6-astra" },
    { id: "gpt-oss-120b", name: "gpt-oss-120b" },
    { id: "gpt-oss-20b", name: "gpt-oss-20b" },
    { id: "grok-4-5", name: "grok-4-5" },
    { id: "grok-4-6", name: "grok-4-6" },
    { id: "hy3", name: "hy3" },
    { id: "hy3:free", name: "hy3:free" },
    { id: "hy4-preview", name: "hy4-preview" },
    { id: "kimi-k2-6", name: "kimi-k2-6" },
    { id: "kimi-k2-7-code", name: "kimi-k2-7-code" },
    { id: "kimi-k3", name: "kimi-k3" },
    { id: "laguna-s-2-1:free", name: "laguna-s-2-1:free" },
    { id: "laguna-xs-2-1:free", name: "laguna-xs-2-1:free" },
    { id: "mimo-v2-5", name: "mimo-v2-5" },
    { id: "mimo-v2-5-pro", name: "mimo-v2-5-pro" },
    { id: "mimo-v2-5:free", name: "mimo-v2-5:free" },
    { id: "minimax-m2-7", name: "minimax-m2-7" },
    { id: "minimax-m2-7-highspeed", name: "minimax-m2-7-highspeed" },
    { id: "minimax-m3", name: "minimax-m3" },
    { id: "mistral-medium-3-5:free", name: "mistral-medium-3-5:free" },
    { id: "muse-spark-1-2", name: "muse-spark-1-2" },
    { id: "muse-spark-1-2-contributor", name: "muse-spark-1-2-contributor" },
    { id: "muse-spark-1-2-contributor:free", name: "muse-spark-1-2-contributor:free" },
    { id: "muse-spark-1-3", name: "muse-spark-1-3" },
    { id: "muse-spark-1-3-contributor", name: "muse-spark-1-3-contributor" },
    { id: "muse-spark-1-3-contributor:free", name: "muse-spark-1-3-contributor:free" },
    { id: "nemotron-3-super-120b-a12b", name: "nemotron-3-super-120b-a12b" },
    { id: "nemotron-3-super-120b-a12b:free", name: "nemotron-3-super-120b-a12b:free" },
    { id: "nemotron-3-ultra-550b-a55b", name: "nemotron-3-ultra-550b-a55b" },
    { id: "nemotron-3-ultra-550b-a55b:free", name: "nemotron-3-ultra-550b-a55b:free" },
    { id: "nex-n2-5-pro:free", name: "nex-n2-5-pro:free" },
    { id: "north-mini-code:free", name: "north-mini-code:free" },
    { id: "qwen3-7-plus", name: "qwen3-7-plus" },
    { id: "qwen3-8-flash", name: "qwen3-8-flash" },
    { id: "qwen3-8-max", name: "qwen3-8-max" },
    { id: "step-3-7-flash", name: "step-3-7-flash" },
    { id: "step-3-7-flash:free", name: "step-3-7-flash:free" },
  ],
  features: {
    usage: true,
    usageApikey: true,
  },
  // Kenari's catalogue moves fast (new model ids weekly). The seed list above is
  // for offline model pickers; unknown ids still route, and the live list is
  // fetched on demand by the dashboard.
  passthroughModels: true,
  modelsFetcher: { url: "https://kenari.id/v1/models", type: "kenari" },
};
